### ISSUE TITLE
Long-press sensitivity / 3D Touch

### ISSUE THREAD

**Issue by ekkesa** [thomasloven/lovelace-long-press#2]
I'm really enjoying your long-press.js for lovelace, but now I'm getting greedy after using it for a while... I find that it is very sensitive, scrolling up & down on the screen when one by accident start on the picture element it envokes the long-press opening up more-info. Though not a train smash, but not ideal. What is the possibility of using 3d-touch vs long-press or perhaps making long-press less sensitive? I played with the value of this.timer = setTimeout((e) => this.onHold(), 300); which yielded various results, but none better. If the value is too high, the save image dialogue pops up. Again, thanks for your trouble, just wanted to give some feedback...

Perhaps, one could reset the timer if movement is detected? Not sure - Just a guess

**Comment by thomasloven** [comment]
Closing this issue since the plugin is deprecated.
The functionality now exists in home-assistant core.

For future reference, 3d touch will probably never happen unless implemented by the home-assistant app. It's not detectable from a website - as far as I know.
