### ISSUE TITLE
Uncaught NotSupportedError

### ISSUE THREAD

**Issue by SeLLeRoNe** [thomasloven/lovelace-long-press#4]
Hi Thomas,
first of all, thanks! Thanks for all the cards you made, are amazing!

I am facing an issue, well not an issue, a strange log entry with this long-press card:
```
long-press.js?track=true:101:16 Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
```
I did a check and the only other place here "long-press" i referenced is:
```
www/lovelace/cards/card-tools.js:    customElements.whenDefined("long-press").then(() => {
www/lovelace/cards/card-tools.js:      const longpress = document.body.querySelector("long-press");
www/lovelace/cards/long-press.js:customElements.define('long-press', LongPress)
```
Is the long-press card not meant to be used 'cause deprecated or included in card-tools or is there any other strange thing I am not seeing?

Well, either way, hope this help you and/or someone else will notice this error in the logs :)

Thanks
Andrea

**Comment by thomasloven** [comment]
Hi. This card is deprecated because all of its functionality (though improved, more beautiful and more stable) is built into lovelace since several months.

Look up `tap_action` and `hold_action` for the entity/card you are trying to modify.

**Comment by SeLLeRoNe** [comment]
Thanks for the response, I'd imagine that but ask was making sure of it :)
